### ISSUE TITLE
Pratica 01 - Repositório próprio

### ISSUE THREAD

**Issue by savate** [savate/GCMS-Laercio-Rodrigues#1]
[README](https://github.com/savate/GCMS-Laercio-Rodrigues/edit/main/README.md)

**Comment by ramidedantas** [comment]
@savate Formate o README como está no meu repositório, incluindo seu nome. Me maque aqui quando fizer.

**Comment by savate** [comment]
@ramidedantas mudança realizada.

**Comment by ramidedantas** [comment]
Ok @savate, pode fechar agora.
